services:
  postgres:
    image: postgres:17.2-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SuperSecr3t}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped

volumes:
    postgres:
    pgadmin:

networks:
  default:
    name: bookshelf
