services:
  #begin Fluss cluster
  coordinator-server:
    image: ghcr.io/nhuantho/docker/apache/fluss:0.8.0-incubating-20260301-0
    command: coordinatorServer
    depends_on:
      - zookeeper
    environment:
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        bind.listeners: FLUSS://coordinator-server:9123
        datalake.format: paimon
        datalake.paimon.metastore: filesystem
        datalake.paimon.warehouse: /tmp/paimon
#        datalake.format: paimon
#        datalake.paimon.metastore: filesystem
#        datalake.paimon.warehouse: s3://datalake/paimon/warehouse
#        datalake.paimon.s3.endpoint: http://minio:9000
#        datalake.paimon.s3.access-key: zXZekZpwOtBipYq6nV9a
#        datalake.paimon.s3.secret-key: zXZekZpwOtBipYq6nV9a
#        datalake.paimon.s3.path.style.access: true
  tablet-server:
    image: ghcr.io/nhuantho/docker/apache/fluss:0.8.0-incubating-20260301-0
    command: tabletServer
    depends_on:
      - coordinator-server
    environment:
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        bind.listeners: FLUSS://tablet-server:9123
        datalake.format: paimon
        datalake.paimon.metastore: filesystem
        datalake.paimon.warehouse: /tmp/paimon
        kv.snapshot.interval: 0s
  zookeeper:
    restart: always
    image: zookeeper:3.9.2
  #end

networks:
  default:
    name: bookshelf
